from myapp.views.admin.user import *
from myapp.views.admin.feedback import *
from myapp.views.admin.advertise import *
from myapp.views.admin.login_log import *
from myapp.views.admin.classification import *
from myapp.views.admin.overview import *
from myapp.views.admin.notice import *
from myapp.views.admin.song import *
from myapp.views.admin.language import *
from myapp.views.admin.comment import *
from myapp.views.admin.playList import *