from myapp.views.index.user import *
from myapp.views.index.feedback import *
from myapp.views.index.classification import *
from myapp.views.index.notice import *
from myapp.views.index.song import *
from myapp.views.index.language import *
from myapp.views.index.comment import *
from myapp.views.index.browse_history import *
from myapp.views.index.file_upload import *
from myapp.views.index.playList import *
