# Generated by Django 5.2.1 on 2025-05-29 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='分类ID', primary_key=True, serialize=False),
        ),
    ]
