# Generated by Django 5.2.1 on 2025-05-29 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_classification_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='语言ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='语言名称，如中文、英文', max_length=50)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.ForeignKey(blank=True, help_text='歌曲语言', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.language'),
        ),
    ]
