# Generated by Django 5.2.1 on 2025-05-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_language_alter_song_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classification',
            old_name='title',
            new_name='name',
        ),
    ]
