# Generated by Django 5.2.1 on 2025-05-30 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_title_classification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(blank=True, help_text='上传用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_song', to='myapp.user'),
        ),
    ]
