# Generated by Django 5.2.1 on 2025-05-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='recommend_count',
        ),
    ]
