# Generated by Django 5.2.1 on 2025-05-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_song_recommend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='comment_count',
            field=models.IntegerField(default=0, help_text='评论数'),
        ),
    ]
