# Generated by Django 5.2.1 on 2025-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='cover',
            field=models.CharField(help_text='广告图片', max_length=500, null=True),
        ),
    ]
