# Generated by Django 5.2.1 on 2025-06-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_feedback_feedback_screenshot_alter_song_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='cover',
            field=models.CharField(blank=True, help_text='广告图片', max_length=200, null=True),
        ),
    ]
