# Generated by Django 5.2.1 on 2025-06-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_systemnotice_is_global_systemnotice_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='source',
            field=models.CharField(blank=True, help_text='音频文件', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', help_text='性别', max_length=1, null=True),
        ),
    ]
