# Generated by Django 5.2.1 on 2025-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_song_source_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '禁用')], default='0', help_text='评论状态', max_length=1),
        ),
    ]
