# Generated by Django 5.2.1 on 2025-06-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_comment_update_time_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.CharField(blank=True, help_text='歌词文件', max_length=200, null=True),
        ),
    ]
