# Generated by Django 5.2.1 on 2025-06-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_song_lyrics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='lyrics',
            new_name='lyric',
        ),
    ]
