# Generated by Django 5.2.1 on 2025-06-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '禁用')], default='0', help_text='状态', max_length=1),
        ),
    ]
