# Generated by Django 5.2.1 on 2025-06-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_playlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='classification',
        ),
        migrations.AddField(
            model_name='song',
            name='classifications',
            field=models.ManyToManyField(blank=True, help_text='所属分类（可多选）', related_name='songs', to='myapp.classification'),
        ),
    ]
