# Generated by Django 5.2.1 on 2025-06-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_song_classifications_song_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='classifications',
            field=models.ManyToManyField(blank=True, help_text='所属分类（可多选）', related_name='playlists', to='myapp.classification'),
        ),
    ]
