# Generated by Django 5.2.1 on 2025-06-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_playlist_classifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='classifications',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='collect_count',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='collect_users',
        ),
        migrations.RemoveField(
            model_name='song',
            name='collect',
        ),
        migrations.RemoveField(
            model_name='song',
            name='collect_count',
        ),
        migrations.RemoveField(
            model_name='song',
            name='language',
        ),
        migrations.RemoveField(
            model_name='song',
            name='like',
        ),
        migrations.RemoveField(
            model_name='song',
            name='like_count',
        ),
    ]
