# Generated by Django 5.2.1 on 2025-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_playlist_classifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='classifications',
            field=models.ManyToManyField(blank=True, help_text='所属分类（可多选）', related_name='playlists', to='myapp.classification'),
        ),
    ]
