# Generated by Django 5.2.1 on 2025-06-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_playlist_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.ForeignKey(blank=True, help_text='所属语言', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_song', to='myapp.language'),
        ),
    ]
