# Generated by Django 5.2.1 on 2025-06-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_song_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='collect_users',
            field=models.ManyToManyField(blank=True, help_text='收藏用户', related_name='collected_playlists', to='myapp.user'),
        ),
    ]
